### PR TITLE
UCX: Use separate workers for tx and rx threads

### PR DESCRIPTION
**Pull request by brminich**
Use different UCX workers for send and receive operations. This way send and receive operations would not block each other. 
Receiver worker can be created **without** multi-threading support, because it will be accessed only by the PollRx thread.
Send worker has to be created **with** multi-threading support, because it will be used by ps-lite sending threads and PollTx thread in UCX Van (which is needed to ensure send operations progression in the network).

On certain configurations this changes provides up to 21% performance improvement with push-only and up to 44% with push-pull benchmarks

### CODE REVIEW

**Comment by eric-haibin-lin** [comment]
Hi @brminich , what is the message size you used for testing? I used the following command on the RoCE 200Gb/s machines, but the PUSH_ONLY goodput dropped from 40 Gb/s to 37 Gb/s

```
NUM_KEY_PER_SERVER=400 ARGS="25600 1000000 2" UCX_NET_DEVICES=mlx5_0:1 PS_VERBOSE=0 UCX_HOME=/opt/tiger/haibin.lin/ps-lite-test-benchmark/ucx_shm_roce_build/ NODE_ONE_IP=10.212.255.206 NODE_TWO_IP=10.212.255.207 DMLC_NUM_PORTS=1 SKIP_DEV_ID_CHECK=1 UCX_MAX_RNDV_RAILS=1 DMLC_NUM_GPU_DEV=0 DMLC_NUM_CPU_DEV=1 ENABLE_RECV_BUFFER=0 TEST_NUM_GPU_WORKER=0 TEST_NUM_GPU_SERVER=0 TEST_NUM_CPU_WORKER=1 TEST_NUM_CPU_SERVER=1 numactl -m 1 -N 1  bash ./test.sh 
```

**Comment by eric-haibin-lin** [comment]
I see an increase in Goodput for PUSH_PULL, from 14-15 Gb/s to 15-17 Gb/s

**Comment by brminich** [comment]
```
DMLC_NUM_WORKER=1 DMLC_NUM_SERVER=1 BENCHMARK_NTHREAD=1 NUM_KEY_PER_SERVER=400 DMLC_ENABLE_UCX=1 LOG_DURATION=100 DMLC_PS_ROOT_PORT=12350 ARGS="25600 10000 2 " BYTEPS_UCX_NUMA_AWARE=-1 NODE_TWO_IP=192.168.40.45 NODE_ONE_IP=192.168.40.38  numactl -N 1 -m 1 bash test.sh local &
```
I did not specify `NUM_RAILS=1`

**Comment by eric-haibin-lin** [comment]
@brminich <del> I got even lower Goodput if I change num_rails from 1 to 2.. (33-34 Gb/s Goodput for PUSH_ONLY) </del>
Let me take that back - the network throughput was a bit sporadic at the beginning. After setting large log_duration and wait longer, I see 5%-10% increase in Goodput.

**Comment by eric-haibin-lin** [comment]
Another general question - when the message size is small enough (less than SHORT_THRESHOLD & RDNV_THRESHOLD), does num_rails still affect the performance? 
I assume it should not since the message won't go through RDNV protocols?

**Comment by brminich** [comment]
> Another general question - when the message size is small enough (less than SHORT_THRESHOLD & RDNV_THRESHOLD), does num_rails still affect the performance?
> I assume it should not since the message won't go through RDNV protocols?

No, it should not affect the performance

**Pull request merged**
