### PR TITLE
rdmavan: reduce depth to fix rdmavan OOM with joint mode

### PR DESCRIPTION
**Pull request by Young768**
To avoid oom issue when using rdmavan with joint mode if ```num_workers``` >= 8, this PR set default kStartDepth and kRxDepth to 512,32, respectively

### CODE REVIEW

**Comment by eric-haibin-lin** [comment]
@Young768 pls fix code format

**Comment by Young768** [comment]
@eric-haibin-lin Clang-format was done.

**Comment by ymjiang** [comment]
The default value is tuned for our internal use for most cases. Why don't you use the env var to set the value?

**Comment by eric-haibin-lin** [comment]
> The default value is tuned for our internal use for most cases. Why don't you use the env var to set the value?

I'll make an update to limit this change to the scheduler role only

**Pull request merged**
