### PR TITLE
Add initial UCX Van support

### PR DESCRIPTION
**Pull request by brminich**
To run with UCX need to:
1) Clone or download [UCX](https://github.com/openucx/ucx)
2) Build it with multi-thread support, like below:
`./autogen.sh && ./contrib/configure-release --enable-mt --prefix=$YOUR_UCX_PATH && make install -j`
3) Build ps-lite with UCX by 
`make USE_UCX=1 ADD_CFLAGS="-I${YOUR_UCX_PATH}/include -L${YOUR_UCX_PATH}/lib`
4) Add DMLC_ENABLE_UCX=1 to your run script

### CODE REVIEW

**Comment by ymjiang** [comment]
Thank you very much for the contribution! May I know about the performance number of `ucx_van` running the benchmark script? (e.g., `tests/test_benchmark`)

cc @bobzhuyb

**Comment by bobzhuyb** [comment]
@brminich Thank you very much. We will start testing it.

**Comment by brminich** [comment]
I'll provide the relevant perf numbers soon.
Can you please also enable UCX van CI (added by the second commit)?

**Comment by bobzhuyb** [comment]
I am merging this into a ucx branch, and will merge into byteps branch in the future

**Comment by pleasantrabbit** [comment]
@brminich does the ucx van require the scheduler to start before worker and server nodes? I am seeing some connection errors on servers/workers, and it looks like they are trying to connect to the scheduler before the scheduler is listening.

**Comment by brminich** [comment]
@pleasantrabbit, yes connection establishment retrying is not implemented in the current version

**Comment by pleasantrabbit** [comment]
> @pleasantrabbit, yes connection establishment retrying is not implemented in the current version

@brminich Could you add retrying to the UCX van? Our use case allows the scheduler/worker/server nodes to start up in any order, it's not really usable for us without retrying during connection establishment.

**Comment by brminich** [comment]
@pleasantrabbit. Ok, I'll add it

**Comment by pleasantrabbit** [comment]
> @pleasantrabbit. Ok, I'll add it

@brminich Could you explain what are the possible ways to implement retrying at connection establishment? 

Using the `test_benchmark` test, if I start the worker before the scheduler, on the worker side `ucp_ep_create()` on [this line](https://github.com/bytedance/ps-lite/blob/byteps/src/ucx_van.h#L106) returns `UCS_OK`, but it actually fails and prints an error:
         ```sockcm_ep.c:151  UCX  ERROR failed to connect to my_ip:my_port```
is there a way to know for sure if the connection is successful? From the documentation `ep_params.err_handler.cb` is only called when there's a transport level error.

**Comment by brminich** [comment]
> > @pleasantrabbit. Ok, I'll add it
> 
> @brminich Could you explain what are the possible ways to implement retrying at connection establishment?
> 
> Using the `test_benchmark` test, if I start the worker before the scheduler, on the worker side `ucp_ep_create()` on [this line](https://github.com/bytedance/ps-lite/blob/byteps/src/ucx_van.h#L106) returns `UCS_OK`, but it actually fails and prints an error:
> `sockcm_ep.c:151 UCX ERROR failed to connect to my_ip:my_port`
> is there a way to know for sure if the connection is successful? From the documentation `ep_params.err_handler.cb` is only called when there's a transport level error.

@pleasantrabbit, you can do message message exchange (using AM API for instance). Once it is completed, ep can be considered connected. So you have to wait for either fail or special message.
Are you working on it now?

**Comment by pleasantrabbit** [comment]
> Are you working on it now?

@brminich I am trying to understand how it can be done, just in case you don't have cycles to work on it.

> you can do message message exchange (using AM API for instance). Once it is completed, ep can be considered connected. So you have to wait for either fail or special message.

Do you mean something like https://github.com/bytedance/ps-lite/pull/40? If I do it this way the code never comes out of the do-while loop [here](https://github.com/bytedance/ps-lite/pull/40/files#diff-7ca91ab251bcf87d33847543b2b6040fR128-R132).

**Comment by brminich** [comment]
@pleasantrabbit, please check #42. It works in my environment, but not sure I tested it well enough.
Do you have some kind of acceptance tests?

**Comment by pleasantrabbit** [comment]
@brminich thank you very much for the patch. We don't have acceptance tests specifically for this case. But the patch works as expected in my one-off tests.

**Comment by eric-haibin-lin** [comment]
Hi @brminich thanks for the nice contribution. Is there any performance benchmark result of this implementation? For instance, running test_benchmark.cc?

**Comment by brminich** [comment]
@eric-haibin-lin, do you mean #42? This is just connection establishment change, should not affect performance.

**Comment by eric-haibin-lin** [comment]
Yes, I meant the initial PR 42 :)

**Comment by eric-haibin-lin** [comment]
sorry, I meant PR 31 😂

**Pull request merged**
