### PR TITLE
relax size check

### PR DESCRIPTION
**Pull request by jasperzhong**
refer to https://github.com/dmlc/ps-lite/issues/167

this is a must for gradient compression.

### CODE REVIEW

**Comment by jasperzhong** [comment]
I think this PR should be merged? Since https://github.com/bytedance/byteps/pull/225 has been merged. 

@ymjiang

**Comment by ymjiang** [comment]
Merged. Sorry for the delay.

**Comment by jasonliu747** [comment]
@ymjiang FYI, submodule in byteps is still detached at 2f40b17 which doesn't cover this update.

**Comment by ymjiang** [comment]
> @ymjiang FYI, submodule in byteps is still detached at [2f40b17](https://github.com/bytedance/ps-lite/commit/2f40b17737d7e11902dae0859ff30f36eb7e0417) which doesn't cover this update.

Will fix this in https://github.com/bytedance/byteps/pull/326.

**Pull request merged**
